### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by strutive07** [strutive07/transformer-tensorflow2.0#1]
- [x] model typo fix.
- [x] single gpu learning

- [ ] check multi gpu learning - in progress in GCP
- [ ] check bleu score.(base model)

**Comment by strutive07** [comment]
2019-09-09

- tf 2.0 으로 구현 계속 진행중.
- single gpu로 loss가 어느정도 깍이는것은 확인. 근데 single로는 조금하면 학습이 많이 안됨. 일단 multi gpu 를 해볼 생각중.
- tf2.0 multi gpu example이 별로 없어서 계속 찾아보는중.
- 아직 데이터 사이언스 업계에서 종사중이 아니라 다른 업종이라 GPU 지원을 못받아서 GCP email 돌려막기로 GCP 크레딧으로 해볼 생각중. 오늘 학습 환경 세팅 끝.
- 그래서 이번주에는 tf2.0 multi gpu 학습 진행해볼생각입니다.

- 몇가지 오류를 만났었는데 이게 버그인지 아닌지 살짝 궁금함. 질문 가능?
- tf.keras.preprocessing.text.Tokenizer 로 tokenizing 하였고, tokenizer.sequences_to_texts method로 결과를 뽑아보려했음.
dataset에서 tensor를 뽑아서 넣으면 아래 오류가 발생. 최근 비슷한 에러 메세지가 github issue 등록됬었는데 버그인지 아닌지 모르겠음.
.numpy() 로 numpy로 변환해서 입력하면 잘 되지만 numpy 연산이 느려서 살짝 불만이긴함. (마지막 evalutation 구간에서 발생한 이슈였어서 학습 속도에는 크게 영향 X)\

https://github.com/tensorflow/tensorflow/issues/32139
Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref()
